export const ADD_FAVORITE_BOOK = "ADD_FAVORITE_BOOK";

export const SET_CHARACTER_DATA = "SET_CHARACTER_DATA";

export const REMOVE_FAVORITE_BOOK = "REMOVE_FAVORITE_BOOK";

export const GET_BOOKS = "GET_BOOKS";
